site_name: Neverquest Wiki

theme:
  name: material
  palette:
    scheme: slate
    primary: amber
    accent: amber

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

nav:
  - Home: index.md
  - Items:
    - Aethylsteel Longsword: itemDatabase/Aethylsteel_Longsword.md
  - Subclasses:
    - Druid: mechanics/subclass_Druid.md

extra_css:
  - stylesheets/extra.css
