site_name: Neverquest Wiki

theme:
  name: material
  palette:
    scheme: slate
    primary: purple

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
